# Generated by Django 5.1.4 on 2024-12-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='category',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('HR', 'Human Resources'), ('FIN', 'Finance'), ('MKT', 'Marketing'), ('EDU', 'Education')], default='IT', max_length=50),
        ),
    ]
